logging:
  level: INFO
  loggers:
    org.example: DEBUG

database:
  driverClass: 'com.mysql.cj.jdbc.Driver'
  user: 'root'
  password: 'fakePassword!'
  url: 'jdbc:mysql://localhost:3306/webservices?useSSL=false'